<?php

namespace Database\Seeders;

use App\Models\Delegacion;
use App\Models\Disciplina;
use App\Models\Partido;
use App\Models\Torneo;
use App\Models\User;
use App\Services\TournamentService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Configuración del Torneo, Branding y Carrusel
        $torneo = Torneo::updateOrCreate(
            ['id' => 1],
            [
                'nombre' => 'Juegos Escolares Deportivos y Paradeportivos 2026',
                'subtitulo' => 'Etapa Macrorregional N° 07 · Sede Puno',
                'organizador' => 'Dirección Regional de Educación Puno - MINEDU',
                'sede_principal' => 'Puno',
                'logo_url' => null,
                'portada_url' => '/images/portada_macroregional.jpeg',
                'logo_texto' => 'JEDPA 2026',
                'logo_subtexto' => 'Macroregional Sede Puno',
                'footer_texto' => 'Dirección Regional de Educación Puno - Oficina de Informática. Todos los derechos reservados.',
                'carrusel_slides' => [
                    [
                        'imagen' => '/images/portada_macroregional.jpeg',
                        'titulo' => 'JEDPA Macrorregional 2026',
                        'subtitulo' => 'Sede Puno · Competencia deportiva oficial de la Macro Región Sur',
                    ],
                    [
                        'imagen' => 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80',
                        'titulo' => 'Estadio Enrique Torres Belón',
                        'subtitulo' => 'Fútbol, Atletismo y Ceremonias de Apertura',
                    ],
                    [
                        'imagen' => 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=1200&auto=format&fit=crop&q=80',
                        'titulo' => 'Coliseos Eduardo Rodríguez Ponce de León y UNA',
                        'subtitulo' => 'Básquet, Voleibol, Futsal y Handball de alto nivel escolar',
                    ],
                ],
                'anio' => 2026,
                'avance_porcentaje' => 35,
            ]
        );

        // 2. Delegaciones Oficiales Participantes
        $delegaciones = [
            ['id' => 'dre-puno', 'nombre' => 'DRE Puno (Anfitrión)', 'siglas' => 'PUNO', 'provincia' => 'Puno'],
            ['id' => 'dre-arequipa', 'nombre' => 'DRE Arequipa', 'siglas' => 'AREQUIPA', 'provincia' => 'Arequipa'],
            ['id' => 'dre-tacna', 'nombre' => 'DRE Tacna', 'siglas' => 'TACNA', 'provincia' => 'Tacna'],
            ['id' => 'dre-moquegua', 'nombre' => 'DRE Moquegua', 'siglas' => 'MOQUEGUA', 'provincia' => 'Mariscal Nieto'],
            ['id' => 'dre-cusco', 'nombre' => 'DRE Cusco', 'siglas' => 'CUSCO', 'provincia' => 'Cusco'],
            ['id' => 'dre-madre-de-dios', 'nombre' => 'DRE Madre de Dios', 'siglas' => 'MDD', 'provincia' => 'Tambopata'],
            ['id' => 'ugel-san-roman', 'nombre' => 'UGEL San Román', 'siglas' => 'JULIACA', 'provincia' => 'San Román'],
            ['id' => 'ugel-melgar', 'nombre' => 'UGEL Melgar', 'siglas' => 'MELGAR', 'provincia' => 'Melgar'],
        ];

        foreach ($delegaciones as $del) {
            Delegacion::updateOrCreate(
                ['id' => $del['id']],
                [
                    'nombre' => $del['nombre'],
                    'siglas' => $del['siglas'],
                    'provincia' => $del['provincia'],
                    'puntos' => 0,
                    'pj' => 0,
                    'pg' => 0,
                    'pe' => 0,
                    'pp' => 0,
                    'gf' => 0,
                    'gc' => 0,
                    'dg' => 0,
                ]
            );
        }

        // 3. Disciplinas Deportivas Oficiales (14 Deportes del Cronograma)
        // Deportes Principales (Padres)
        $deportesPrincipales = [
            [
                'id' => 'atletismo',
                'parent_id' => null,
                'slug' => 'atletismo',
                'nombre' => 'Atletismo - Para atletismo',
                'categoria' => 'Cat. A, B y C - D y E',
                'genero' => 'Damas y Varones',
                'tipo' => 'INDIVIDUAL',
                'sistema_puntuacion' => 'INDIVIDUAL',
                'color_acento' => '#f59e0b',
                'foto_url' => 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Pruebas de pista y campo: velocidad, fondo, salto y lanzamiento en pista sintética.',
                'sede_principal' => 'Estadio Enrique Torres Belón · Puno',
                'fechas_cronograma' => '28-Set (9:30 AM) y 29-Set (8:00 AM)',
                'horario_cronograma' => '08:00 AM - 01:00 PM',
                'campeon_actual' => 'DRE Puno (Anfitrión)',
                'podio' => [
                    'oro' => ['delegacion' => 'DRE Puno (Anfitrión)', 'atleta' => 'Diego Quispe C.', 'marca' => '100m - 10.85s'],
                    'plata' => ['delegacion' => 'DRE Arequipa', 'atleta' => 'Mateo Gómez R.', 'marca' => '100m - 11.02s'],
                    'bronce' => ['delegacion' => 'DRE Cusco', 'atleta' => 'Lucas Mamani T.', 'marca' => '100m - 11.20s'],
                ],
            ],
            [
                'id' => 'natacion',
                'parent_id' => null,
                'slug' => 'natacion',
                'nombre' => 'Natación',
                'categoria' => 'Cat. A, B y C',
                'genero' => 'Damas y Varones',
                'tipo' => 'INDIVIDUAL',
                'sistema_puntuacion' => 'INDIVIDUAL',
                'color_acento' => '#06b6d4',
                'foto_url' => 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Pruebas individuales de estilo libre, espalda, pecho y mariposa.',
                'sede_principal' => 'Piscina Municipal de Puno',
                'fechas_cronograma' => '28-Set (10:00 AM) y 29-Set (10:00 AM)',
                'horario_cronograma' => '10:00 AM - 02:00 PM',
                'campeon_actual' => 'DRE Arequipa',
                'podio' => [
                    'oro' => ['delegacion' => 'DRE Arequipa', 'atleta' => 'Sofía Ramos P.', 'marca' => '50m Libre - 27.42s'],
                    'plata' => ['delegacion' => 'DRE Puno (Anfitrión)', 'atleta' => 'Camila Flores M.', 'marca' => '50m Libre - 28.10s'],
                    'bronce' => ['delegacion' => 'DRE Tacna', 'atleta' => 'Valeria Cárdenas', 'marca' => '50m Libre - 28.95s'],
                ],
            ],
            [
                'id' => 'futbol',
                'parent_id' => null,
                'slug' => 'futbol',
                'nombre' => 'Fútbol',
                'categoria' => 'Cat. B y C',
                'genero' => 'Damas y Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'FUTBOL',
                'color_acento' => '#16a34a',
                'foto_url' => 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Fútbol 11 reglamentario en cancha sintética. 2 tiempos de 30 minutos.',
                'sede_principal' => 'Cancha sintética de Fútbol - UNA Puno',
                'fechas_cronograma' => '30-Set, 01-Oct y 02-Oct (9:00 AM)',
                'horario_cronograma' => '09:00 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
            [
                'id' => 'futsal',
                'parent_id' => null,
                'slug' => 'futsal',
                'nombre' => 'Futsal',
                'categoria' => 'Cat. B',
                'genero' => 'Varones y Damas',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'FUTSAL',
                'color_acento' => '#059669',
                'foto_url' => 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Fútbol de salón en coliseo techado. 2 tiempos de 20 minutos corridos.',
                'sede_principal' => 'Coliseo UNA - Puno',
                'fechas_cronograma' => '30-Set, 01-Oct y 02-Oct (9:00 AM)',
                'horario_cronograma' => '09:00 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
            [
                'id' => 'basquet',
                'parent_id' => null,
                'slug' => 'basquet',
                'nombre' => 'Básquet',
                'categoria' => 'Cat. B y C',
                'genero' => 'Damas y Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'BASQUET',
                'color_acento' => '#ea580c',
                'foto_url' => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&auto=format&fit=crop&q=80',
                'descripcion' => '4 periodos de 10 minutos. Aro a 3.05 m de altura.',
                'sede_principal' => 'Coliseo cubierto Eduardo Rodríguez Ponce de León',
                'fechas_cronograma' => '30-Set, 01-Oct y 02-Oct (9:00 AM)',
                'horario_cronograma' => '09:00 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
            [
                'id' => 'voleibol',
                'parent_id' => null,
                'slug' => 'voleibol',
                'nombre' => 'Voleibol',
                'categoria' => 'Cat. B y C',
                'genero' => 'Damas y Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'VOLEIBOL',
                'color_acento' => '#e11d48',
                'foto_url' => 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Al mejor de 2 de 3 sets (a 25 pts; 3er set decisivo a 15 pts).',
                'sede_principal' => 'Coliseo IE Glorioso San Carlos',
                'fechas_cronograma' => '30-Set, 01-Oct y 02-Oct (9:00 AM)',
                'horario_cronograma' => '09:00 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
            [
                'id' => 'voley-playa',
                'parent_id' => null,
                'slug' => 'voley-playa',
                'nombre' => 'Vóley Playa',
                'categoria' => 'Cat. B',
                'genero' => 'Damas y Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'VOLEY_PLAYA',
                'color_acento' => '#d97706',
                'foto_url' => 'https://images.unsplash.com/photo-1592656094267-764a45160876?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Modalidad en arena por parejas al mejor de 2 de 3 sets.',
                'sede_principal' => 'Cancha Vóley Playa - UNA Puno',
                'fechas_cronograma' => '30-Set y 01-Oct (9:00 AM)',
                'horario_cronograma' => '09:00 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
            [
                'id' => 'handball',
                'parent_id' => null,
                'slug' => 'handball',
                'nombre' => 'Handball',
                'categoria' => 'Cat. B',
                'genero' => 'Damas y Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'HANDBALL',
                'color_acento' => '#7c3aed',
                'foto_url' => 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Balonmano escolar: 2 tiempos de 20 minutos con 10 min de descanso.',
                'sede_principal' => 'IE GUE San Carlos',
                'fechas_cronograma' => '30-Set, 01-Oct y 02-Oct (9:00 AM)',
                'horario_cronograma' => '09:00 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
            [
                'id' => 'tenis-mesa',
                'parent_id' => null,
                'slug' => 'tenis-mesa',
                'nombre' => 'Tenis de Mesa',
                'categoria' => 'Cat. B y C',
                'genero' => 'Damas y Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'VOLEIBOL',
                'color_acento' => '#2563eb',
                'foto_url' => 'https://images.unsplash.com/photo-1534158914592-062992fbe900?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Mesas profesionales en el Coliseo Estadio UNA Puno.',
                'sede_principal' => 'Estadio - UNA Puno Puerta tribuna norte',
                'fechas_cronograma' => '28-Set (10:00 AM) y 29-Set (9:00 AM)',
                'horario_cronograma' => '09:00 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
            [
                'id' => 'ajedrez',
                'parent_id' => null,
                'slug' => 'ajedrez',
                'nombre' => 'Ajedrez',
                'categoria' => 'Cat. A y B',
                'genero' => 'Damas y Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'FUTBOL',
                'color_acento' => '#475569',
                'foto_url' => 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Sistema suizo a 5 rondas bajo reglamento FIDE escolar.',
                'sede_principal' => 'IE GUE San Carlos',
                'fechas_cronograma' => '28-Set (9:30 AM) y 29-Set (9:00 AM)',
                'horario_cronograma' => '09:00 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
            [
                'id' => 'tenis-campo',
                'parent_id' => null,
                'slug' => 'tenis-campo',
                'nombre' => 'Tenis de Campo',
                'categoria' => 'Cat. A',
                'genero' => 'Damas y Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'VOLEIBOL',
                'color_acento' => '#84cc16',
                'foto_url' => 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Torneo individual y dobles en superficie de arcilla.',
                'sede_principal' => 'Club de Tiro - Manuel Pino N° 18',
                'fechas_cronograma' => '28-Set (9:30 AM)',
                'horario_cronograma' => '09:30 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
            [
                'id' => 'paleta-fronton',
                'parent_id' => null,
                'slug' => 'paleta-fronton',
                'nombre' => 'Paleta Frontón',
                'categoria' => 'Cat. C',
                'genero' => 'Damas y Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'VOLEIBOL',
                'color_acento' => '#0284c7',
                'foto_url' => 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Canchas reglamentarias en el Complejo deportivo Chanu Chanu.',
                'sede_principal' => 'Complejo deportivo Chanu Chanu',
                'fechas_cronograma' => '28-Set (10:00 AM)',
                'horario_cronograma' => '10:00 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
            [
                'id' => 'gimnasia',
                'parent_id' => null,
                'slug' => 'gimnasia',
                'nombre' => 'Gimnasia Rítmica y Artística',
                'categoria' => 'Cat. A',
                'genero' => 'Damas y Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'FUTBOL',
                'color_acento' => '#ec4899',
                'foto_url' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Rutinas de suelo, aparatos y rítmica escolar.',
                'sede_principal' => 'Coliseo IE GUE San Carlos',
                'fechas_cronograma' => '29-Set (9:30 AM)',
                'horario_cronograma' => '09:30 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
            [
                'id' => 'taekwondo',
                'parent_id' => null,
                'slug' => 'taekwondo',
                'nombre' => 'Taekwondo',
                'categoria' => 'Cat. A',
                'genero' => 'Damas y Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'FUTBOL',
                'color_acento' => '#dc2626',
                'foto_url' => 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800&auto=format&fit=crop&q=80',
                'descripcion' => 'Modalidades Kyorugi (combate) y Poomsae (formas) oficiales.',
                'sede_principal' => 'Auditorio Consejo Regional del Deporte - IPD',
                'fechas_cronograma' => '29-Set (9:30 AM)',
                'horario_cronograma' => '09:30 AM',
                'campeon_actual' => null,
                'podio' => null,
            ],
        ];

        foreach ($deportesPrincipales as $dp) {
            Disciplina::updateOrCreate(['id' => $dp['id']], $dp);
        }

        // Subcategorías por Deporte (Hijas vinculadas con parent_id)
        $subcategorias = [
            // Subcategorías de Fútbol
            [
                'id' => 'futbol-b-varones',
                'parent_id' => 'futbol',
                'slug' => 'futbol-b-varones',
                'nombre' => 'Fútbol Cat. B Varones',
                'categoria' => 'Cat. B',
                'genero' => 'Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'FUTBOL',
                'color_acento' => '#16a34a',
                'sede_principal' => 'Cancha sintética de Fútbol - UNA Puno',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '09:00 AM',
            ],
            [
                'id' => 'futbol-b-damas',
                'parent_id' => 'futbol',
                'slug' => 'futbol-b-damas',
                'nombre' => 'Fútbol Cat. B Damas',
                'categoria' => 'Cat. B',
                'genero' => 'Damas',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'FUTBOL',
                'color_acento' => '#15803d',
                'sede_principal' => 'Cancha sintética de Fútbol - UNA Puno',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '10:30 AM',
            ],
            [
                'id' => 'futbol-c-varones',
                'parent_id' => 'futbol',
                'slug' => 'futbol-c-varones',
                'nombre' => 'Fútbol Cat. C Varones',
                'categoria' => 'Cat. C',
                'genero' => 'Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'FUTBOL',
                'color_acento' => '#166534',
                'sede_principal' => 'Cancha sintética de Fútbol - UNA Puno',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '01:00 PM',
            ],
            [
                'id' => 'futbol-c-damas',
                'parent_id' => 'futbol',
                'slug' => 'futbol-c-damas',
                'nombre' => 'Fútbol Cat. C Damas',
                'categoria' => 'Cat. C',
                'genero' => 'Damas',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'FUTBOL',
                'color_acento' => '#14532d',
                'sede_principal' => 'Cancha sintética de Fútbol - UNA Puno',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '02:30 PM',
            ],

            // Subcategorías de Futsal
            [
                'id' => 'futsal-b-varones',
                'parent_id' => 'futsal',
                'slug' => 'futsal-b-varones',
                'nombre' => 'Futsal Cat. B Varones',
                'categoria' => 'Cat. B',
                'genero' => 'Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'FUTSAL',
                'color_acento' => '#059669',
                'sede_principal' => 'Coliseo UNA - Puno',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '09:00 AM',
            ],
            [
                'id' => 'futsal-b-damas',
                'parent_id' => 'futsal',
                'slug' => 'futsal-b-damas',
                'nombre' => 'Futsal Cat. B Damas',
                'categoria' => 'Cat. B',
                'genero' => 'Damas',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'FUTSAL',
                'color_acento' => '#047857',
                'sede_principal' => 'Coliseo UNA - Puno',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '10:15 AM',
            ],

            // Subcategorías de Básquet
            [
                'id' => 'basquet-b-varones',
                'parent_id' => 'basquet',
                'slug' => 'basquet-b-varones',
                'nombre' => 'Básquet Cat. B Varones',
                'categoria' => 'Cat. B',
                'genero' => 'Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'BASQUET',
                'color_acento' => '#ea580c',
                'sede_principal' => 'Coliseo cubierto ERPL',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '09:00 AM',
            ],
            [
                'id' => 'basquet-b-damas',
                'parent_id' => 'basquet',
                'slug' => 'basquet-b-damas',
                'nombre' => 'Básquet Cat. B Damas',
                'categoria' => 'Cat. B',
                'genero' => 'Damas',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'BASQUET',
                'color_acento' => '#c2410c',
                'sede_principal' => 'Coliseo cubierto ERPL',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '10:30 AM',
            ],
            [
                'id' => 'basquet-c-varones',
                'parent_id' => 'basquet',
                'slug' => 'basquet-c-varones',
                'nombre' => 'Básquet Cat. C Varones',
                'categoria' => 'Cat. C',
                'genero' => 'Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'BASQUET',
                'color_acento' => '#9a3412',
                'sede_principal' => 'Coliseo cubierto ERPL',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '01:00 PM',
            ],
            [
                'id' => 'basquet-c-damas',
                'parent_id' => 'basquet',
                'slug' => 'basquet-c-damas',
                'nombre' => 'Básquet Cat. C Damas',
                'categoria' => 'Cat. C',
                'genero' => 'Damas',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'BASQUET',
                'color_acento' => '#7c2d12',
                'sede_principal' => 'Coliseo cubierto ERPL',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '02:30 PM',
            ],

            // Subcategorías de Voleibol
            [
                'id' => 'voleibol-b-damas',
                'parent_id' => 'voleibol',
                'slug' => 'voleibol-b-damas',
                'nombre' => 'Voleibol Cat. B Damas',
                'categoria' => 'Cat. B',
                'genero' => 'Damas',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'VOLEIBOL',
                'color_acento' => '#e11d48',
                'sede_principal' => 'Coliseo IE Glorioso San Carlos',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '09:00 AM',
            ],
            [
                'id' => 'voleibol-b-varones',
                'parent_id' => 'voleibol',
                'slug' => 'voleibol-b-varones',
                'nombre' => 'Voleibol Cat. B Varones',
                'categoria' => 'Cat. B',
                'genero' => 'Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'VOLEIBOL',
                'color_acento' => '#be123c',
                'sede_principal' => 'Coliseo IE Glorioso San Carlos',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '10:30 AM',
            ],
            [
                'id' => 'voleibol-c-damas',
                'parent_id' => 'voleibol',
                'slug' => 'voleibol-c-damas',
                'nombre' => 'Voleibol Cat. C Damas',
                'categoria' => 'Cat. C',
                'genero' => 'Damas',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'VOLEIBOL',
                'color_acento' => '#9f1239',
                'sede_principal' => 'Coliseo IE Glorioso San Carlos',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '01:00 PM',
            ],
            [
                'id' => 'voleibol-c-varones',
                'parent_id' => 'voleibol',
                'slug' => 'voleibol-c-varones',
                'nombre' => 'Voleibol Cat. C Varones',
                'categoria' => 'Cat. C',
                'genero' => 'Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'VOLEIBOL',
                'color_acento' => '#881337',
                'sede_principal' => 'Coliseo IE Glorioso San Carlos',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '02:30 PM',
            ],

            // Subcategorías de Handball
            [
                'id' => 'handball-b-varones',
                'parent_id' => 'handball',
                'slug' => 'handball-b-varones',
                'nombre' => 'Handball Cat. B Varones',
                'categoria' => 'Cat. B',
                'genero' => 'Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'HANDBALL',
                'color_acento' => '#7c3aed',
                'sede_principal' => 'IE GUE San Carlos',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '09:00 AM',
            ],
            [
                'id' => 'handball-b-damas',
                'parent_id' => 'handball',
                'slug' => 'handball-b-damas',
                'nombre' => 'Handball Cat. B Damas',
                'categoria' => 'Cat. B',
                'genero' => 'Damas',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'HANDBALL',
                'color_acento' => '#6d28d9',
                'sede_principal' => 'IE GUE San Carlos',
                'fechas_cronograma' => '30-Set, 01-Oct, 02-Oct',
                'horario_cronograma' => '10:30 AM',
            ],

            // Subcategorías de Vóley Playa
            [
                'id' => 'voley-playa-b-damas',
                'parent_id' => 'voley-playa',
                'slug' => 'voley-playa-b-damas',
                'nombre' => 'Vóley Playa Cat. B Damas',
                'categoria' => 'Cat. B',
                'genero' => 'Damas',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'VOLEY_PLAYA',
                'color_acento' => '#d97706',
                'sede_principal' => 'Cancha Vóley Playa - UNA Puno',
                'fechas_cronograma' => '30-Set y 01-Oct',
                'horario_cronograma' => '09:00 AM',
            ],
            [
                'id' => 'voley-playa-b-varones',
                'parent_id' => 'voley-playa',
                'slug' => 'voley-playa-b-varones',
                'nombre' => 'Vóley Playa Cat. B Varones',
                'categoria' => 'Cat. B',
                'genero' => 'Varones',
                'tipo' => 'COLECTIVO',
                'sistema_puntuacion' => 'VOLEY_PLAYA',
                'color_acento' => '#b45309',
                'sede_principal' => 'Cancha Vóley Playa - UNA Puno',
                'fechas_cronograma' => '30-Set y 01-Oct',
                'horario_cronograma' => '10:30 AM',
            ],
        ];

        foreach ($subcategorias as $sub) {
            Disciplina::updateOrCreate(['id' => $sub['id']], $sub);
        }

        // 4. Usuarios: Administrador y Delegados para cada deporte
        $admin = User::updateOrCreate(
            ['username' => 'admin'],
            [
                'name' => 'Administrador General DREP',
                'email' => 'admin@drepuno.gob.pe',
                'password' => Hash::make('admin123'),
                'role' => 'ADMIN',
                'delegacion_id' => 'dre-puno',
                'activo' => true,
            ]
        );

        $delegadosConfig = [
            ['user' => 'delegado.futbol', 'name' => 'Delegado Oficial Fútbol', 'email' => 'futbol@drepuno.gob.pe', 'deportes' => ['futbol', 'futbol-b-varones', 'futbol-b-damas', 'futbol-c-varones', 'futbol-c-damas']],
            ['user' => 'delegado.futsal', 'name' => 'Delegado Oficial Futsal', 'email' => 'futsal@drepuno.gob.pe', 'deportes' => ['futsal', 'futsal-b-varones', 'futsal-b-damas']],
            ['user' => 'delegado.basquet', 'name' => 'Delegado Oficial Básquet', 'email' => 'basquet@drepuno.gob.pe', 'deportes' => ['basquet', 'basquet-b-varones', 'basquet-b-damas', 'basquet-c-varones', 'basquet-c-damas']],
            ['user' => 'delegado.voley', 'name' => 'Delegado Oficial Voleibol', 'email' => 'voley@drepuno.gob.pe', 'deportes' => ['voleibol', 'voleibol-b-damas', 'voleibol-b-varones', 'voleibol-c-damas', 'voleibol-c-varones', 'voley-playa', 'voley-playa-b-damas', 'voley-playa-b-varones']],
            ['user' => 'delegado.handball', 'name' => 'Delegado Oficial Handball', 'email' => 'handball@drepuno.gob.pe', 'deportes' => ['handball', 'handball-b-varones', 'handball-b-damas']],
            ['user' => 'delegado.atletismo', 'name' => 'Delegado Oficial Atletismo', 'email' => 'atletismo@drepuno.gob.pe', 'deportes' => ['atletismo']],
            ['user' => 'delegado.natacion', 'name' => 'Delegado Oficial Natación', 'email' => 'natacion@drepuno.gob.pe', 'deportes' => ['natacion']],
            ['user' => 'delegado.tenismesa', 'name' => 'Delegado Oficial Tenis de Mesa', 'email' => 'tenismesa@drepuno.gob.pe', 'deportes' => ['tenis-mesa']],
            ['user' => 'delegado.ajedrez', 'name' => 'Delegado Oficial Ajedrez', 'email' => 'ajedrez@drepuno.gob.pe', 'deportes' => ['ajedrez']],
        ];

        foreach ($delegadosConfig as $dc) {
            $user = User::updateOrCreate(
                ['username' => $dc['user']],
                [
                    'name' => $dc['name'],
                    'email' => $dc['email'],
                    'password' => Hash::make('123456'),
                    'role' => 'DELEGADO',
                    'delegacion_id' => 'dre-puno',
                    'activo' => true,
                ]
            );

            // Asignar permisos granulares de disciplinas en la tabla pivote
            DB::table('delegado_disciplinas')->where('user_id', $user->id)->delete();
            foreach ($dc['deportes'] as $depId) {
                if (Disciplina::where('id', $depId)->exists()) {
                    DB::table('delegado_disciplinas')->insert([
                        'user_id' => $user->id,
                        'disciplina_id' => $depId,
                    ]);
                }
            }
        }

        // 5. Partidos con Fechas del Cronograma Oficial JEDPA 2026
        $partidosData = [
            // Fútbol Cat. B Varones
            [
                'id' => 'part-fut-01',
                'disciplina_id' => 'futbol-b-varones',
                'ronda_numero' => 1,
                'ronda_nombre' => 'Fecha 1',
                'local_id' => 'dre-puno',
                'visitante_id' => 'dre-tacna',
                'local_goles' => 3,
                'visitante_goles' => 1,
                'ganador_id' => 'dre-puno',
                'estado' => 'FINALIZADO',
                'fecha' => '2026-09-30',
                'horario' => '09:00 AM',
                'cancha' => 'Cancha sintética UNA - Campo 1',
                'es_wo' => false,
                'foto_evidencia' => null,
                'observaciones' => 'Partido inaugural de Fútbol Cat. B Varones.',
            ],
            [
                'id' => 'part-fut-02',
                'disciplina_id' => 'futbol-b-varones',
                'ronda_numero' => 1,
                'ronda_nombre' => 'Fecha 1',
                'local_id' => 'dre-arequipa',
                'visitante_id' => 'dre-cusco',
                'local_goles' => 2,
                'visitante_goles' => 2,
                'ganador_id' => null,
                'estado' => 'FINALIZADO',
                'fecha' => '2026-09-30',
                'horario' => '10:30 AM',
                'cancha' => 'Cancha sintética UNA - Campo 1',
                'es_wo' => false,
                'foto_evidencia' => null,
                'observaciones' => 'Empate reñido en los últimos minutos.',
            ],
            [
                'id' => 'part-fut-03',
                'disciplina_id' => 'futbol-b-varones',
                'ronda_numero' => 2,
                'ronda_nombre' => 'Fecha 2',
                'local_id' => 'dre-puno',
                'visitante_id' => 'dre-arequipa',
                'local_goles' => null,
                'visitante_goles' => null,
                'ganador_id' => null,
                'estado' => 'PROGRAMADO',
                'fecha' => '2026-10-01',
                'horario' => '09:00 AM',
                'cancha' => 'Cancha sintética UNA - Campo 1',
                'es_wo' => false,
                'foto_evidencia' => null,
                'observaciones' => 'Clásico regional de la Macro Región Sur.',
            ],
            [
                'id' => 'part-fut-04',
                'disciplina_id' => 'futbol-b-varones',
                'ronda_numero' => 2,
                'ronda_nombre' => 'Fecha 2',
                'local_id' => 'dre-tacna',
                'visitante_id' => 'dre-cusco',
                'local_goles' => null,
                'visitante_goles' => null,
                'ganador_id' => null,
                'estado' => 'PROGRAMADO',
                'fecha' => '2026-10-01',
                'horario' => '10:30 AM',
                'cancha' => 'Cancha sintética UNA - Campo 1',
                'es_wo' => false,
                'foto_evidencia' => null,
                'observaciones' => null,
            ],
            [
                'id' => 'part-fut-05',
                'disciplina_id' => 'futbol-b-varones',
                'ronda_numero' => 3,
                'ronda_nombre' => 'Gran Final',
                'local_id' => 'dre-puno',
                'visitante_id' => 'dre-cusco',
                'local_goles' => null,
                'visitante_goles' => null,
                'ganador_id' => null,
                'estado' => 'PROGRAMADO',
                'fecha' => '2026-10-02',
                'horario' => '11:00 AM',
                'cancha' => 'Cancha sintética UNA - Campo 1',
                'es_wo' => false,
                'foto_evidencia' => null,
                'observaciones' => 'Partido definitorio por la medalla de Oro.',
            ],

            // Voleibol Cat. B Damas
            [
                'id' => 'part-vol-01',
                'disciplina_id' => 'voleibol-b-damas',
                'ronda_numero' => 1,
                'ronda_nombre' => 'Fecha 1',
                'local_id' => 'dre-arequipa',
                'visitante_id' => 'dre-moquegua',
                'local_goles' => 2,
                'visitante_goles' => 0,
                'ganador_id' => 'dre-arequipa',
                'estado' => 'FINALIZADO',
                'fecha' => '2026-09-30',
                'horario' => '09:00 AM',
                'cancha' => 'Coliseo IE Glorioso San Carlos',
                'es_wo' => false,
                'foto_evidencia' => null,
                'observaciones' => 'Sets: 25-18, 25-20 (Victoria 2-0 = 3 pts).',
            ],
            [
                'id' => 'part-vol-02',
                'disciplina_id' => 'voleibol-b-damas',
                'ronda_numero' => 1,
                'ronda_nombre' => 'Fecha 1',
                'local_id' => 'dre-puno',
                'visitante_id' => 'dre-tacna',
                'local_goles' => 2,
                'visitante_goles' => 1,
                'ganador_id' => 'dre-puno',
                'estado' => 'FINALIZADO',
                'fecha' => '2026-09-30',
                'horario' => '10:30 AM',
                'cancha' => 'Coliseo IE Glorioso San Carlos',
                'es_wo' => false,
                'foto_evidencia' => null,
                'observaciones' => 'Sets: 25-22, 21-25, 15-11 (Victoria 2-1 = 2 pts para Puno, 1 pt para Tacna).',
            ],
            [
                'id' => 'part-vol-03',
                'disciplina_id' => 'voleibol-b-damas',
                'ronda_numero' => 2,
                'ronda_nombre' => 'Fecha 2',
                'local_id' => 'dre-puno',
                'visitante_id' => 'dre-arequipa',
                'local_goles' => null,
                'visitante_goles' => null,
                'ganador_id' => null,
                'estado' => 'PROGRAMADO',
                'fecha' => '2026-10-01',
                'horario' => '10:00 AM',
                'cancha' => 'Coliseo IE Glorioso San Carlos',
                'es_wo' => false,
                'foto_evidencia' => null,
                'observaciones' => null,
            ],

            // Básquet Cat. B Varones
            [
                'id' => 'part-bas-01',
                'disciplina_id' => 'basquet-b-varones',
                'ronda_numero' => 1,
                'ronda_nombre' => 'Fecha 1',
                'local_id' => 'dre-tacna',
                'visitante_id' => 'dre-arequipa',
                'local_goles' => 54,
                'visitante_goles' => 48,
                'ganador_id' => 'dre-tacna',
                'estado' => 'FINALIZADO',
                'fecha' => '2026-09-30',
                'horario' => '09:00 AM',
                'cancha' => 'Coliseo cubierto ERPL',
                'es_wo' => false,
                'foto_evidencia' => null,
                'observaciones' => 'Básquet oficial: Ganador recibe 2 pts, perdedor recibe 1 pt.',
            ],
            [
                'id' => 'part-bas-02',
                'disciplina_id' => 'basquet-b-varones',
                'ronda_numero' => 1,
                'ronda_nombre' => 'Fecha 1',
                'local_id' => 'dre-puno',
                'visitante_id' => 'dre-cusco',
                'local_goles' => null,
                'visitante_goles' => null,
                'ganador_id' => null,
                'estado' => 'PROGRAMADO',
                'fecha' => '2026-09-30',
                'horario' => '10:30 AM',
                'cancha' => 'Coliseo cubierto ERPL',
                'es_wo' => false,
                'foto_evidencia' => null,
                'observaciones' => null,
            ],
        ];

        foreach ($partidosData as $p) {
            Partido::updateOrCreate(['id' => $p['id']], $p);
        }

        // 6. Recalcular tabla de posiciones general inicial
        $service = app(TournamentService::class);
        $service->recalcularTablaPosiciones();
    }
}
